---
mdw_repo_file: /etc/yum.repos.d/mdw.repo
mdw_setenv_search_root: /data

mdw_repo_name: mdw
mdw_repo_description: MDW Artifactory
mdw_repo_baseurl: "https://artifactory.example.com/artifactory/rpm-mdw/"
mdw_repo_enabled: true
mdw_repo_gpgcheck: false

mdw_runtime_rpm_patterns:
  - '^mdw-jdk'
  - '^mdw-asf-tomcat'
  - '^mdw-jws-tomcat'